### ISSUE TITLE
Bug: co-op doesn’t work

### ISSUE THREAD

**Issue by nwfistere** [nwfistere/bloodlines#14]
Seems as though coop doesn’t work with the mod

**Comment by nwfistere** [comment]
```log
[15:10:01.280] During invoking native->managed trampoline
Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at VampireSurvivors.Objects.Characters.SpriteOutlinerControl.ShowOutline (UnityEngine.SpriteRenderer spriteRenderer, UnityEngine.Color colour) [0x00000] in <00000000000000000000000000000000>:0
  at VampireSurvivors.Objects.Characters.CharacterController.ShowMultiplayerIndicator () [0x00000] in <00000000000000000000000000000000>:0
  at VampireSurvivors.Framework.GameManager.ResumeGame () [0x00000] in <00000000000000000000000000000000>:0
  at VampireSurvivors.Framework.GameManager.InitializeGameSession () [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at DMD<Il2CppVampireSurvivors.Framework.GameManager::InitializeGameSession>(GameManager this)
   at (il2cpp -> managed) InitializeGameSession(IntPtr , Il2CppMethodInfo* )
[15:10:01.291] During invoking native->managed trampoline
Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at VampireSurvivors.Objects.Characters.SpriteOutlinerControl.ShowOutline (UnityEngine.SpriteRenderer spriteRenderer, UnityEngine.Color colour) [0x00000] in <00000000000000000000000000000000>:0
  at VampireSurvivors.Objects.Characters.CharacterController.ShowMultiplayerIndicator () [0x00000] in <00000000000000000000000000000000>:0
  at VampireSurvivors.Framework.GameManager.ResumeGame () [0x00000] in <00000000000000000000000000000000>:0
  at VampireSurvivors.Framework.GameManager.InitializeGameSession () [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at DMD<Il2CppVampireSurvivors.Framework.GameManager::InitializeGameSession>(GameManager this)
   at (il2cpp -> managed) InitializeGameSession(IntPtr , Il2CppMethodInfo* )
```
