### ISSUE TITLE
Zip  file not properly converting

### ISSUE THREAD

**Issue by Sinnerofstans** [nwfistere/bloodlines#7]
so when i open vampire survivors with the zip file in the folder for some reason it generates a blank folder with my characters name and the zip stays

**Comment by Sinnerofstans** [comment]
The log says:
[23:16:20.761] [Bloodlines] Error: Newtonsoft.Json.JsonReaderException: Input string '0.1' is not a valid integer. Path 'character[0].speed', line 45, position 15.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Bloodlines.CharacterManager.GetFileDto(String json, Type& type)
   at Bloodlines.CharacterManager.handleJsonFileString(String jsonFilePath, String json)
   at Bloodlines.CharacterManager.ParseExistingCharacterFiles()
   at Bloodlines.CharacterManager..ctor(String ZipPath, String ExtractPath)
[23:16:20.763] [Bloodlines] Submit an issue for this exception.

**Comment by Sinnerofstans** [comment]
Sorry for the disturbance i just set the speed to 0.1

**Comment by nwfistere** [comment]
Hi @Sinnerofstans,

Thanks for taking a look at this mod!

I have a pull request (#6) to add a website gui for creating custom character packs. The website should help with issues such as these. 

Feel free to open up any other issues if you run into anything.

Thanks,

Nick

**Comment by nwfistere** [comment]
Reopening: The existing characters allow for floating point numbers in the stat properties (e.g. speed). This needs to be fixed.

**Comment by nwfistere** [comment]
#9 merged, each type of passive should have the right data type when using a v0.2 skin.
